# Generated by Django 4.2.30 on 2026-08-03 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
        ('orders', '0002_orderitem_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان دسته')),
                ('type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=10, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته تراکنش مالی',
                'verbose_name_plural': 'دسته\u200cهای تراکنش مالی',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], max_length=10, verbose_name='نوع')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (تومان)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='ثبت خودکار سیستم')),
                ('occurred_at', models.DateField(verbose_name='تاریخ تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.transactioncategory', verbose_name='دسته')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط')),
                ('related_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='orders.order', verbose_name='سفارش مرتبط')),
                ('related_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='vendors.vendor', verbose_name='فروشنده مرتبط')),
            ],
            options={
                'verbose_name': 'تراکنش مالی',
                'verbose_name_plural': 'تراکنش\u200cهای مالی',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
