# Generated by Django 4.2.30 on 2026-08-02 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multivendor_enabled', models.BooleanField(default=False, verbose_name='حالت چندفروشندگی فعال باشد')),
                ('default_commission_percent', models.DecimalField(blank=True, decimal_places=2, help_text='در صورت خالی بودن، فعلاً کارمزدی محاسبه نمی\u200cشود.', max_digits=5, null=True, verbose_name='درصد کارمزد پیش\u200cفرض پلتفرم')),
            ],
            options={
                'verbose_name': 'تنظیمات پلتفرم',
                'verbose_name_plural': 'تنظیمات پلتفرم',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150, verbose_name='نام فروشگاه')),
                ('store_slug', models.SlugField(blank=True, max_length=170, unique=True, verbose_name='اسلاگ فروشگاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات فروشگاه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='لوگو')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تاییدشده'), ('rejected', 'رد شده'), ('suspended', 'معلق\u200cشده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('commission_percent', models.DecimalField(blank=True, decimal_places=2, help_text='اگر خالی باشد، درصد پیش\u200cفرض پلتفرم استفاده می\u200cشود.', max_digits=5, null=True, verbose_name='درصد کارمزد اختصاصی (اختیاری)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مالک فروشگاه')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
                'ordering': ['-created_at'],
            },
        ),
    ]
