# Generated by Django 4.2.30 on 2026-08-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='در حالت تک\u200cفروشگاهی خالی می\u200cماند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='vendors.vendor', verbose_name='فروشنده'),
        ),
    ]
