# Generated by Django 4.2.30 on 2026-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('manage_roles', 'می\u200cتواند نقش\u200cها و دسترسی\u200cهای کاربران را مدیریت کند'), ('manage_platform_settings', 'می\u200cتواند تنظیمات کلی پلتفرم را تغییر دهد')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
